# Generated by Django 3.2.1 on 2024-03-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimento',
            old_name='Investimento',
            new_name='investimento',
        ),
    ]
